/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.awt.Color;
import java.awt.Image;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Juan PC
 */
public class PantallaHeladeria extends javax.swing.JFrame {

    public PantallaHeladeria() {
        initComponents();
        fillLists();
        transparencia();
        setButtonGroup1AndComboCheckGray();        
        disableBaniado();
        disableButtonAgregar();
        disableButtonQuitar();
        disableButtonContinuar();
        disablejRadioButtonGusto1();
        disablejRadioButtonGustos2();
        disablejRadioButtonGustos3();
        disablejRadioButtonGustos4();
        obtenerImagenSuperiorEraDeHielo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void fillLists() {
        DefaultListModel<String> listModelGustos = new DefaultListModel<>();
        listaGustos.setModel(listModelGustos);

        DefaultListModel<String> listModelGustosSeleccionados = new DefaultListModel<>();
        listaGustosSeleccionados.setModel(listModelGustosSeleccionados);

        DefaultListModel<String> modelGustos = (DefaultListModel) listaGustos.getModel();

        modelGustos.addElement("Frutillas a la crema");
        modelGustos.addElement("Frutilla");
        modelGustos.addElement("Durazno");
        modelGustos.addElement("Banana Split");
        modelGustos.addElement("Limon");
        modelGustos.addElement("Quinotos a la crema");
        modelGustos.addElement("Cerezas a la crema");
        modelGustos.addElement("Chocolate");
        modelGustos.addElement("Chocolate con nuez");
        modelGustos.addElement("Chocolate con Almendras");
        modelGustos.addElement("Chocolate Rocher");
        modelGustos.addElement("Chocolate Blanco");
        modelGustos.addElement("Tramontana");
        modelGustos.addElement("Sambayon");
        modelGustos.addElement("Vainilla");
        modelGustos.addElement("Crema Americana");
        modelGustos.addElement("Crema Rusa");
        modelGustos.addElement("Crema Flan");
        modelGustos.addElement("Crema del cielo");
        modelGustos.addElement("Dulce de leche");
        modelGustos.addElement("Dulce de leche granizado");
        modelGustos.addElement("Dulce de leche Bombón");
        modelGustos.addElement("Dulce de leche Brownie");
        modelGustos.addElement("Menta granizada");
        modelGustos.addElement("Mascarpone");
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton3 = new javax.swing.JRadioButton();
        buttonGroupTipoDeHelado = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        lbERADEHIELO = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        radioCucurucho = new javax.swing.JRadioButton();
        radioVasito = new javax.swing.JRadioButton();
        labelPote = new javax.swing.JLabel();
        radioUnCuartoKg = new javax.swing.JRadioButton();
        radioUnMedioKg = new javax.swing.JRadioButton();
        radioUnKg = new javax.swing.JRadioButton();
        labelTipoDeHelado = new javax.swing.JLabel();
        labelCantidadDeGustos = new javax.swing.JLabel();
        checkBoxBaniadoEnChocolate = new javax.swing.JCheckBox();
        jRadioButton1Gusto = new javax.swing.JRadioButton();
        jRadioButton2Gustos = new javax.swing.JRadioButton();
        jRadioButton3Gustos = new javax.swing.JRadioButton();
        jRadioButton4Gustos = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        panelGustos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaGustos = new javax.swing.JList<>();
        buttonAgregar = new javax.swing.JButton();
        panelGustosSeleccionados = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaGustosSeleccionados = new javax.swing.JList<>();
        buttonQuitar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        labelTotalAPagar = new javax.swing.JLabel();
        lbTotalAPagar = new javax.swing.JLabel();
        buttonContinuar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jRadioButton3.setText("jRadioButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbERADEHIELO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Arme su helado", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(51, 204, 255));

        radioCucurucho.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroupTipoDeHelado.add(radioCucurucho);
        radioCucurucho.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        radioCucurucho.setForeground(new java.awt.Color(255, 255, 255));
        radioCucurucho.setText("Cucurucho");
        radioCucurucho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCucuruchoActionPerformed(evt);
            }
        });

        radioVasito.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroupTipoDeHelado.add(radioVasito);
        radioVasito.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        radioVasito.setForeground(new java.awt.Color(255, 255, 255));
        radioVasito.setText("Vasito");
        radioVasito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVasitoActionPerformed(evt);
            }
        });

        labelPote.setBackground(new java.awt.Color(255, 255, 51));
        labelPote.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        labelPote.setForeground(new java.awt.Color(255, 255, 255));
        labelPote.setText("Pote:");

        radioUnCuartoKg.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroupTipoDeHelado.add(radioUnCuartoKg);
        radioUnCuartoKg.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        radioUnCuartoKg.setForeground(new java.awt.Color(255, 255, 255));
        radioUnCuartoKg.setText("1/4 KG");
        radioUnCuartoKg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioUnCuartoKgActionPerformed(evt);
            }
        });

        radioUnMedioKg.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroupTipoDeHelado.add(radioUnMedioKg);
        radioUnMedioKg.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        radioUnMedioKg.setForeground(new java.awt.Color(255, 255, 255));
        radioUnMedioKg.setText("1/2 KG");
        radioUnMedioKg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioUnMedioKgActionPerformed(evt);
            }
        });

        radioUnKg.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroupTipoDeHelado.add(radioUnKg);
        radioUnKg.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        radioUnKg.setForeground(new java.awt.Color(255, 255, 255));
        radioUnKg.setText("1 KG");
        radioUnKg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioUnKgActionPerformed(evt);
            }
        });

        labelTipoDeHelado.setBackground(new java.awt.Color(255, 255, 255));
        labelTipoDeHelado.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        labelTipoDeHelado.setForeground(new java.awt.Color(255, 255, 255));
        labelTipoDeHelado.setText("TIPO DE HELADO");

        labelCantidadDeGustos.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        labelCantidadDeGustos.setForeground(new java.awt.Color(255, 255, 255));
        labelCantidadDeGustos.setText("CANTIDAD DE GUSTOS");

        checkBoxBaniadoEnChocolate.setBackground(new java.awt.Color(153, 153, 153));
        checkBoxBaniadoEnChocolate.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        checkBoxBaniadoEnChocolate.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxBaniadoEnChocolate.setText("BAÑADO EN CHOCOLATE");
        checkBoxBaniadoEnChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxBaniadoEnChocolateActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1Gusto);
        jRadioButton1Gusto.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jRadioButton1Gusto.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1Gusto.setText("1 Gusto");
        jRadioButton1Gusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1GustoActionPerformed(evt);
            }
        });

        jRadioButton2Gustos.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(jRadioButton2Gustos);
        jRadioButton2Gustos.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jRadioButton2Gustos.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2Gustos.setText("2 Gustos");
        jRadioButton2Gustos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2GustosActionPerformed(evt);
            }
        });

        jRadioButton3Gustos.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(jRadioButton3Gustos);
        jRadioButton3Gustos.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jRadioButton3Gustos.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3Gustos.setText("3 Gustos");
        jRadioButton3Gustos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3GustosActionPerformed(evt);
            }
        });

        jRadioButton4Gustos.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(jRadioButton4Gustos);
        jRadioButton4Gustos.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jRadioButton4Gustos.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4Gustos.setText("4 Gustos");
        jRadioButton4Gustos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4GustosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(labelTipoDeHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(radioVasito)
                                .addGap(108, 108, 108))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(radioCucurucho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelPote, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(radioUnCuartoKg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioUnMedioKg))
                            .addComponent(radioUnKg))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelCantidadDeGustos)
                        .addGap(77, 77, 77))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBoxBaniadoEnChocolate)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jRadioButton3Gustos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                    .addComponent(jRadioButton4Gustos))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jRadioButton1Gusto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton2Gustos))))
                        .addContainerGap(13, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCantidadDeGustos, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTipoDeHelado))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioCucurucho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelPote, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(radioVasito)
                                .addGap(94, 94, 94))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton1Gusto)
                                    .addComponent(jRadioButton2Gustos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton3Gustos)
                                    .addComponent(jRadioButton4Gustos))
                                .addGap(18, 18, 18)
                                .addComponent(checkBoxBaniadoEnChocolate)
                                .addGap(72, 72, 72))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(radioUnCuartoKg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioUnMedioKg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioUnKg)
                        .addContainerGap())))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Seleccion de gustos", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        panelGustos.setBackground(new java.awt.Color(153, 153, 153));
        panelGustos.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Gustos", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        listaGustos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        listaGustos.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jScrollPane1.setViewportView(listaGustos);

        buttonAgregar.setText("Agregar");
        buttonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGustosLayout = new javax.swing.GroupLayout(panelGustos);
        panelGustos.setLayout(panelGustosLayout);
        panelGustosLayout.setHorizontalGroup(
            panelGustosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGustosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelGustosLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(buttonAgregar)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        panelGustosLayout.setVerticalGroup(
            panelGustosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGustosLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAgregar))
        );

        panelGustosSeleccionados.setBackground(new java.awt.Color(153, 153, 153));
        panelGustosSeleccionados.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Gustos seleccionados", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        listaGustosSeleccionados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        listaGustosSeleccionados.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jScrollPane2.setViewportView(listaGustosSeleccionados);

        buttonQuitar.setText("Quitar");
        buttonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonQuitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGustosSeleccionadosLayout = new javax.swing.GroupLayout(panelGustosSeleccionados);
        panelGustosSeleccionados.setLayout(panelGustosSeleccionadosLayout);
        panelGustosSeleccionadosLayout.setHorizontalGroup(
            panelGustosSeleccionadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGustosSeleccionadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGustosSeleccionadosLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(buttonQuitar)
                .addGap(57, 57, 57))
        );
        panelGustosSeleccionadosLayout.setVerticalGroup(
            panelGustosSeleccionadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGustosSeleccionadosLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonQuitar))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(panelGustos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(panelGustosSeleccionados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGustosSeleccionados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGustos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Facturacion", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        labelTotalAPagar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        labelTotalAPagar.setForeground(new java.awt.Color(255, 255, 255));
        labelTotalAPagar.setText("TOTAL A PAGAR");

        lbTotalAPagar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lbTotalAPagar.setForeground(new java.awt.Color(255, 255, 255));
        lbTotalAPagar.setText(" ");
        lbTotalAPagar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonContinuar.setBackground(new java.awt.Color(255, 153, 153));
        buttonContinuar.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        buttonContinuar.setText("Continuar");
        buttonContinuar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 0), 1, true));
        buttonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(labelTotalAPagar)
                .addGap(27, 27, 27)
                .addComponent(lbTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(buttonContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTotalAPagar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/342589d1b09070c21fb3ea24eaa48175--cellphone-wallpapers-iphone-backgrounds.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbERADEHIELO, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbERADEHIELO, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(550, 550, 550)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void buttonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonQuitarActionPerformed
        String gustoSeleccionado = listaGustosSeleccionados.getSelectedValue();

        if (gustoSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Primero seleccione un gusto a quitar", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultListModel<String> modelGustos = (DefaultListModel<String>) listaGustosSeleccionados.getModel();
            DefaultListModel<String> modelGustosSeleccionados = (DefaultListModel<String>) listaGustos.getModel();

            modelGustosSeleccionados.addElement(gustoSeleccionado);
            modelGustos.removeElement(gustoSeleccionado);
        }
    }//GEN-LAST:event_buttonQuitarActionPerformed

    private void buttonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarActionPerformed
        String gustoASeleccionar = listaGustos.getSelectedValue();

        if (gustoASeleccionar == null) {
            JOptionPane.showMessageDialog(this, "Primero seleccione un gusto a agregar ", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (jRadioButton1Gusto.isSelected() == true) {

            if (listaGustosSeleccionados.getModel().getSize() != 1) {
                DefaultListModel<String> modelGustos = (DefaultListModel<String>) listaGustos.getModel();
                DefaultListModel<String> modelGustosSeleccionados = (DefaultListModel<String>) listaGustosSeleccionados.getModel();

                modelGustosSeleccionados.addElement(gustoASeleccionar);
                modelGustos.removeElement(gustoASeleccionar);
            } else {
                JOptionPane.showMessageDialog(this, "Usted ya cuenta con 1 gusto seleccionado", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else if (jRadioButton2Gustos.isSelected() == true) {
            if (listaGustosSeleccionados.getModel().getSize() != 2) {
                DefaultListModel<String> modelGustos = (DefaultListModel<String>) listaGustos.getModel();
                DefaultListModel<String> modelGustosSeleccionados = (DefaultListModel<String>) listaGustosSeleccionados.getModel();

                modelGustosSeleccionados.addElement(gustoASeleccionar);
                modelGustos.removeElement(gustoASeleccionar);
            } else {
                JOptionPane.showMessageDialog(this, "Usted ya cuenta con 2 gustos seleccionados", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else if (jRadioButton3Gustos.isSelected() == true) {
            if (listaGustosSeleccionados.getModel().getSize() != 3) {
                DefaultListModel<String> modelGustos = (DefaultListModel<String>) listaGustos.getModel();
                DefaultListModel<String> modelGustosSeleccionados = (DefaultListModel<String>) listaGustosSeleccionados.getModel();

                modelGustosSeleccionados.addElement(gustoASeleccionar);
                modelGustos.removeElement(gustoASeleccionar);
            } else {
                JOptionPane.showMessageDialog(this, "Usted ya cuenta con 3 gustos seleccionados", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else if (jRadioButton4Gustos.isSelected() == true) {
            if (listaGustosSeleccionados.getModel().getSize() != 4) {
                DefaultListModel<String> modelGustos = (DefaultListModel<String>) listaGustos.getModel();
                DefaultListModel<String> modelGustosSeleccionados = (DefaultListModel<String>) listaGustosSeleccionados.getModel();

                modelGustosSeleccionados.addElement(gustoASeleccionar);
                modelGustos.removeElement(gustoASeleccionar);
            } else {
                JOptionPane.showMessageDialog(this, "Usted ya cuenta con 4 gustos seleccionados", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        if (listaGustosSeleccionados.getModel().getSize() > 0) {
            enableButtonContinuar();
        }
    }//GEN-LAST:event_buttonAgregarActionPerformed

    private void jRadioButton4GustosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4GustosActionPerformed
        //((DefaultListModel)listaGustosSeleccionados.getModel()).clear();
        //fillLists();
        jRadioButton4Gustos.setActionCommand("4 gustos");
    }//GEN-LAST:event_jRadioButton4GustosActionPerformed

    private void jRadioButton3GustosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3GustosActionPerformed
        //((DefaultListModel)listaGustosSeleccionados.getModel()).clear();
        jRadioButton3Gustos.setActionCommand("3 gustos");
        if (listaGustosSeleccionados.getModel().getSize() > 3) {
            fillLists();
            disableButtonContinuar();
        }
    }//GEN-LAST:event_jRadioButton3GustosActionPerformed

    private void jRadioButton2GustosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2GustosActionPerformed
        //((DefaultListModel)listaGustosSeleccionados.getModel()).clear();
        jRadioButton2Gustos.setActionCommand("2 gustos");
        if (listaGustosSeleccionados.getModel().getSize() > 2) {
            fillLists();
            disableButtonContinuar();
        }
    }//GEN-LAST:event_jRadioButton2GustosActionPerformed

    private void jRadioButton1GustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1GustoActionPerformed
        // ((DefaultListModel)listaGustosSeleccionados.getModel()).clear();
        jRadioButton1Gusto.setActionCommand("1 gusto");
        if (listaGustosSeleccionados.getModel().getSize() > 1) {
            fillLists();
            disableButtonContinuar();
        }
    }//GEN-LAST:event_jRadioButton1GustoActionPerformed

    private void checkBoxBaniadoEnChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxBaniadoEnChocolateActionPerformed
        precioCucuruchoBaniado();
    }//GEN-LAST:event_checkBoxBaniadoEnChocolateActionPerformed

    private void radioUnKgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioUnKgActionPerformed
        radioUnKg.setActionCommand("1 kg");
        jRadioButton4Gustos.setForeground(Color.WHITE);
        jRadioButton3Gustos.setForeground(Color.WHITE);
        jRadioButton2Gustos.setForeground(Color.WHITE);
        jRadioButton1Gusto.setForeground(Color.WHITE);

        disableBaniado();
        checkBoxBaniadoEnChocolate.setForeground(Color.GRAY);
        enableButtonAgregar();
        enableButtonQuitar();
        disableButtonContinuar();
        enablejRadioButtonGusto1();
        enablejRadioButtonGustos2();
        enablejRadioButtonGustos3();
        enablejRadioButtonGustos4();
        ((DefaultListModel) listaGustosSeleccionados.getModel()).clear();
        buttonGroup1.clearSelection();
        lbTotalAPagar.setText(" $135");
        fillLists();
    }//GEN-LAST:event_radioUnKgActionPerformed

    private void radioUnMedioKgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioUnMedioKgActionPerformed
        radioUnMedioKg.setActionCommand("1/2 kg");
        jRadioButton4Gustos.setForeground(Color.WHITE);
        jRadioButton3Gustos.setForeground(Color.WHITE);
        jRadioButton2Gustos.setForeground(Color.WHITE);
        jRadioButton1Gusto.setForeground(Color.WHITE);

        disableBaniado();
        checkBoxBaniadoEnChocolate.setForeground(Color.GRAY);
        enableButtonAgregar();
        enableButtonQuitar();
        disableButtonContinuar();
        enablejRadioButtonGusto1();
        enablejRadioButtonGustos2();
        enablejRadioButtonGustos3();
        disablejRadioButtonGustos4();
        jRadioButton4Gustos.setForeground(Color.GRAY);
        ((DefaultListModel) listaGustosSeleccionados.getModel()).clear();
        buttonGroup1.clearSelection();
        lbTotalAPagar.setText(" $125");
        fillLists();
    }//GEN-LAST:event_radioUnMedioKgActionPerformed

    private void radioUnCuartoKgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioUnCuartoKgActionPerformed
        radioUnCuartoKg.setActionCommand("1/4 kg");
        jRadioButton4Gustos.setForeground(Color.WHITE);
        jRadioButton3Gustos.setForeground(Color.WHITE);
        jRadioButton2Gustos.setForeground(Color.WHITE);
        jRadioButton1Gusto.setForeground(Color.WHITE);

        disableBaniado();
        checkBoxBaniadoEnChocolate.setForeground(Color.GRAY);
        enableButtonAgregar();
        enableButtonQuitar();
        disableButtonContinuar();
        enablejRadioButtonGusto1();
        enablejRadioButtonGustos2();
        disablejRadioButtonGustos3();
        disablejRadioButtonGustos4();
        jRadioButton3Gustos.setForeground(Color.GRAY);
        jRadioButton4Gustos.setForeground(Color.GRAY);
        ((DefaultListModel) listaGustosSeleccionados.getModel()).clear();
        buttonGroup1.clearSelection();
        /*fillcomboBoxCantidadGustos(4);*/
        lbTotalAPagar.setText(" $115");
        fillLists();
    }//GEN-LAST:event_radioUnCuartoKgActionPerformed

    private void radioVasitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVasitoActionPerformed
        radioVasito.setActionCommand("vasito");
        jRadioButton4Gustos.setForeground(Color.WHITE);
        jRadioButton3Gustos.setForeground(Color.WHITE);
        jRadioButton2Gustos.setForeground(Color.WHITE);
        jRadioButton1Gusto.setForeground(Color.WHITE);

        disableBaniado();
        checkBoxBaniadoEnChocolate.setForeground(Color.GRAY);
        enableButtonAgregar();
        enableButtonQuitar();
        disableButtonContinuar();
        enablejRadioButtonGusto1();
        enablejRadioButtonGustos2();
        disablejRadioButtonGustos3();
        disablejRadioButtonGustos4();
        jRadioButton3Gustos.setForeground(Color.GRAY);
        jRadioButton4Gustos.setForeground(Color.GRAY);
        ((DefaultListModel) listaGustosSeleccionados.getModel()).clear();
        buttonGroup1.clearSelection();
        /*fillcomboBoxCantidadGustos(3);*/
        lbTotalAPagar.setText(" $100");
        fillLists();
    }//GEN-LAST:event_radioVasitoActionPerformed

    private void radioCucuruchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCucuruchoActionPerformed
        radioCucurucho.setActionCommand("cucurucho");
        jRadioButton4Gustos.setForeground(Color.WHITE);
        jRadioButton3Gustos.setForeground(Color.WHITE);
        jRadioButton2Gustos.setForeground(Color.WHITE);
        jRadioButton1Gusto.setForeground(Color.WHITE);

        enableBaniado();
        checkBoxBaniadoEnChocolate.setForeground(Color.WHITE);
        enableButtonAgregar();
        enableButtonQuitar();
        disableButtonContinuar();
        enablejRadioButtonGusto1();
        enablejRadioButtonGustos2();
        disablejRadioButtonGustos3();
        jRadioButton3Gustos.setForeground(Color.GRAY);
        disablejRadioButtonGustos4();
        jRadioButton4Gustos.setForeground(Color.GRAY);
        ((DefaultListModel) listaGustosSeleccionados.getModel()).clear();
        buttonGroup1.clearSelection();
        lbTotalAPagar.setText(" $110");
        fillLists();

    }//GEN-LAST:event_radioCucuruchoActionPerformed

    private void buttonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonContinuarActionPerformed
        String radioTipoDeHelado = buttonGroupTipoDeHelado.getSelection().getActionCommand();
        String radioCantidadDeGustos = buttonGroup1.getSelection().getActionCommand();
        String precio = lbTotalAPagar.getText();
        //Bañado
        if ((jRadioButton1Gusto.isSelected() == true) && (checkBoxBaniadoEnChocolate.isSelected() == true)) {
            if (listaGustosSeleccionados.getModel().getSize() != 1) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar 1 gusto para poder continuar", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                DefaultListModel<String> modelGustosSeleccionados = (DefaultListModel<String>) listaGustosSeleccionados.getModel();
                Object[] botones = {" Confirmar pedido", " Volver al pedido", "Cancelar pedido"};
                String[] botones1 = {" boton uno", " boton dos", "boton N"};
                int siONo = JOptionPane.showOptionDialog(this, "Usted esta pidiendo: Un " + radioTipoDeHelado + " bañado en chocolate" + " con " + radioCantidadDeGustos + " sabor: " + modelGustosSeleccionados.toString() +", el precio total es " + precio +" pesos" , "Información", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null/*icono*/, botones, botones1[0]);
                if (siONo == 0) {
                    JOptionPane.showMessageDialog(this, "Su pedido fue confirmado ", "Información", JOptionPane.INFORMATION_MESSAGE);
                    restaurarSelecciones();
                    disableButtonContinuar();
                } else if (siONo == 2) {
                    JOptionPane.showMessageDialog(this, "Pedido cancelado ", "Información", JOptionPane.WARNING_MESSAGE);
                    restaurarSelecciones();
                    disableButtonContinuar();
                }

            }
        }
        if ((jRadioButton2Gustos.isSelected() == true) && (checkBoxBaniadoEnChocolate.isSelected() == true)) {
            if (listaGustosSeleccionados.getModel().getSize() != 2) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar 2 gustos para poder continuar", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                DefaultListModel<String> modelGustosSeleccionados = (DefaultListModel<String>) listaGustosSeleccionados.getModel();
                Object[] botones = {" Confirmar pedido", " Volver al pedido", "Cancelar pedido"};
                String[] botones1 = {" boton uno", " boton dos", "boton N"};
                int siONo = JOptionPane.showOptionDialog(this, "Usted esta pidiendo: Un " + radioTipoDeHelado + " bañado en chocolate" + " con " + radioCantidadDeGustos + " sabor: " + modelGustosSeleccionados.toString() +", el precio total es " + precio +" pesos" , "Información", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null/*icono*/, botones, botones1[0]);
                if (siONo == 0) {
                    JOptionPane.showMessageDialog(this, "Su pedido fue confirmado ", "Información", JOptionPane.INFORMATION_MESSAGE);
                    restaurarSelecciones();
                    disableButtonContinuar();
                } else if (siONo == 2) {
                    JOptionPane.showMessageDialog(this, "Pedido cancelado ", "Información", JOptionPane.WARNING_MESSAGE);
                    restaurarSelecciones();
                    disableButtonContinuar();
                }

            }
        }

        //Sin bañar 
        if ((jRadioButton1Gusto.isSelected() == true) && (checkBoxBaniadoEnChocolate.isSelected() == false)) {
            if (listaGustosSeleccionados.getModel().getSize() != 1) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar 1 gusto para poder continuar", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                DefaultListModel<String> modelGustosSeleccionados = (DefaultListModel<String>) listaGustosSeleccionados.getModel();
                Object[] botones = {" Confirmar pedido", " Volver al pedido", "Cancelar pedido"};
                String[] botones1 = {" boton uno", " boton dos", "boton N"};
                int siONo = JOptionPane.showOptionDialog(this, "Usted esta pidiendo: Un " + radioTipoDeHelado + " con " + radioCantidadDeGustos + " sabor: " + modelGustosSeleccionados.toString() +", el precio total es " + precio +" pesos" , "Información", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null/*icono*/, botones, botones1[0]);
                if (siONo == 0) {
                    JOptionPane.showMessageDialog(this, "Su pedido fue confirmado ", "Información", JOptionPane.INFORMATION_MESSAGE);
                    restaurarSelecciones();
                    disableButtonContinuar();
                } else if (siONo == 2) {
                    JOptionPane.showMessageDialog(this, "Pedido cancelado ", "Información", JOptionPane.WARNING_MESSAGE);
                    restaurarSelecciones();
                    disableButtonContinuar();
                }

            }
        }

        if ((jRadioButton2Gustos.isSelected() == true) && (checkBoxBaniadoEnChocolate.isSelected() == false)) {
            if (listaGustosSeleccionados.getModel().getSize() != 2) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar 2 gustos para poder continuar", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                DefaultListModel<String> modelGustosSeleccionados = (DefaultListModel<String>) listaGustosSeleccionados.getModel();
                Object[] botones = {" Confirmar pedido", " Volver al pedido", "Cancelar pedido"};
                String[] botones1 = {" boton uno", " boton dos", "boton N"};
                int siONo = JOptionPane.showOptionDialog(this, "Usted esta pidiendo: Un " + radioTipoDeHelado + " con " + radioCantidadDeGustos + " sabor: " + modelGustosSeleccionados.toString() +", el precio total es " + precio +" pesos" , "Información", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null/*icono*/, botones, botones1[0]);
                if (siONo == 0) {
                    JOptionPane.showMessageDialog(this, "Su pedido fue confirmado ", "Información", JOptionPane.INFORMATION_MESSAGE);
                    restaurarSelecciones();
                    disableButtonContinuar();
                } else if (siONo == 2) {
                    JOptionPane.showMessageDialog(this, "Pedido cancelado ", "Información", JOptionPane.WARNING_MESSAGE);
                    restaurarSelecciones();
                    disableButtonContinuar();
                }
            }
        }
        if (jRadioButton3Gustos.isSelected() == true) {
            if (listaGustosSeleccionados.getModel().getSize() != 3) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar 3 gustos para poder continuar", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                DefaultListModel<String> modelGustosSeleccionados = (DefaultListModel<String>) listaGustosSeleccionados.getModel();
                Object[] botones = {" Confirmar pedido", " Volver al pedido", "Cancelar pedido"};
                String[] botones1 = {" boton uno", " boton dos", "boton N"};
                int siONo = JOptionPane.showOptionDialog(this, "Usted esta pidiendo: Un " + radioTipoDeHelado + " con " + radioCantidadDeGustos + " sabor: " + modelGustosSeleccionados.toString() +", el precio total es " + precio +" pesos" , "Información", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null/*icono*/, botones, botones1[0]);
                if (siONo == 0) {
                    JOptionPane.showMessageDialog(this, "Su pedido fue confirmado ", "Información", JOptionPane.INFORMATION_MESSAGE);
                    restaurarSelecciones();
                    disableButtonContinuar();
                } else if (siONo == 2) {
                    JOptionPane.showMessageDialog(this, "Pedido cancelado ", "Información", JOptionPane.WARNING_MESSAGE);
                    restaurarSelecciones();
                    disableButtonContinuar();
                }
            }
        }
        if (jRadioButton4Gustos.isSelected() == true) {
            if (listaGustosSeleccionados.getModel().getSize() != 4) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar 4 gustos para poder continuar", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                DefaultListModel<String> modelGustosSeleccionados = (DefaultListModel<String>) listaGustosSeleccionados.getModel();
                Object[] botones = {" Confirmar pedido", " Volver al pedido", "Cancelar pedido"};
                String[] botones1 = {" boton uno", " boton dos", "boton N"};
                int siONo = JOptionPane.showOptionDialog(this, "Usted esta pidiendo: Un " + radioTipoDeHelado + " con " + radioCantidadDeGustos + " sabor: " + modelGustosSeleccionados.toString() +", el precio total es " + precio +" pesos" , "Información", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null/*icono*/, botones, botones1[0]);
                if (siONo == 0) {
                    JOptionPane.showMessageDialog(this, "Su pedido fue confirmado ", "Información", JOptionPane.INFORMATION_MESSAGE);
                    restaurarSelecciones();
                    disableButtonContinuar();
                } else if (siONo == 2) {
                    JOptionPane.showMessageDialog(this, "Pedido cancelado ", "Información", JOptionPane.WARNING_MESSAGE);
                    restaurarSelecciones();
                    disableButtonContinuar();
                }
            }
        }
    }//GEN-LAST:event_buttonContinuarActionPerformed
// main comentado
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PantallaHeladeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PantallaHeladeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PantallaHeladeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PantallaHeladeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PantallaHeladeria().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAgregar;
    private javax.swing.JButton buttonContinuar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroupTipoDeHelado;
    private javax.swing.JButton buttonQuitar;
    private javax.swing.JCheckBox checkBoxBaniadoEnChocolate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1Gusto;
    private javax.swing.JRadioButton jRadioButton2Gustos;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton3Gustos;
    private javax.swing.JRadioButton jRadioButton4Gustos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCantidadDeGustos;
    private javax.swing.JLabel labelPote;
    private javax.swing.JLabel labelTipoDeHelado;
    private javax.swing.JLabel labelTotalAPagar;
    private javax.swing.JLabel lbERADEHIELO;
    private javax.swing.JLabel lbTotalAPagar;
    private javax.swing.JList<String> listaGustos;
    private javax.swing.JList<String> listaGustosSeleccionados;
    private javax.swing.JPanel panelGustos;
    private javax.swing.JPanel panelGustosSeleccionados;
    private javax.swing.JRadioButton radioCucurucho;
    private javax.swing.JRadioButton radioUnCuartoKg;
    private javax.swing.JRadioButton radioUnKg;
    private javax.swing.JRadioButton radioUnMedioKg;
    private javax.swing.JRadioButton radioVasito;
    // End of variables declaration//GEN-END:variables

    private void disableBaniado() {
        checkBoxBaniadoEnChocolate.setEnabled(false);
        checkBoxBaniadoEnChocolate.setSelected(false);
    }

    private void enableBaniado() {
        checkBoxBaniadoEnChocolate.setEnabled(true);
    }

    private void disableButtonAgregar() {
        buttonAgregar.setEnabled(false);
    }

    private void enableButtonAgregar() {
        buttonAgregar.setEnabled(true);

    }

    private void disablejRadioButtonGusto1() {
        jRadioButton1Gusto.setEnabled(false);
        jRadioButton1Gusto.setSelected(false);
    }

    private void enablejRadioButtonGusto1() {
        jRadioButton1Gusto.setEnabled(true);
    }

    private void disablejRadioButtonGustos2() {
        jRadioButton2Gustos.setEnabled(false);
        jRadioButton2Gustos.setSelected(false);
    }

    private void enablejRadioButtonGustos2() {
        jRadioButton2Gustos.setEnabled(true);
    }

    private void disablejRadioButtonGustos3() {
        jRadioButton3Gustos.setEnabled(false);
        jRadioButton3Gustos.setSelected(false);
    }

    private void enablejRadioButtonGustos3() {
        jRadioButton3Gustos.setEnabled(true);
    }

    private void disablejRadioButtonGustos4() {
        jRadioButton4Gustos.setEnabled(false);
        jRadioButton4Gustos.setSelected(false);

    }

    private void enablejRadioButtonGustos4() {
        jRadioButton4Gustos.setEnabled(true);
    }

    private void precioCucuruchoBaniado() {
        if (checkBoxBaniadoEnChocolate.isSelected() == true) {
            lbTotalAPagar.setText(" $120");
        } else {
            lbTotalAPagar.setText(" $110");
        }

    }

    private void disableButtonQuitar() {
        buttonQuitar.setEnabled(false);
    }

    private void enableButtonQuitar() {
        buttonQuitar.setEnabled(true);
    }

    private void disableButtonContinuar() {
        buttonContinuar.setEnabled(false);
    }

    private void enableButtonContinuar() {
        buttonContinuar.setEnabled(true);
    }

    private void transparencia() {
        jPanel6.setOpaque(false);
        jPanel3.setOpaque(false);
        jPanel2.setOpaque(false);
        panelGustos.setOpaque(false);
        panelGustosSeleccionados.setOpaque(false);
    }

    private void restaurarSelecciones() {
        jRadioButton4Gustos.setForeground(Color.GRAY);
        jRadioButton3Gustos.setForeground(Color.GRAY);
        jRadioButton2Gustos.setForeground(Color.GRAY);
        jRadioButton1Gusto.setForeground(Color.GRAY);
        checkBoxBaniadoEnChocolate.setForeground(Color.GRAY);
        disablejRadioButtonGusto1();
        disablejRadioButtonGustos2();
        disablejRadioButtonGustos3();
        disablejRadioButtonGustos4();
        disableBaniado();
        disableButtonAgregar();
        disableButtonQuitar();
        disableButtonContinuar();
        buttonGroupTipoDeHelado.clearSelection();
        buttonGroup1.clearSelection();
        fillLists();
        lbTotalAPagar.setText(""); 
    }
    
    private void setButtonGroup1AndComboCheckGray(){
        checkBoxBaniadoEnChocolate.setForeground(Color.GRAY);
        jRadioButton4Gustos.setForeground(Color.GRAY);
        jRadioButton3Gustos.setForeground(Color.GRAY);
        jRadioButton2Gustos.setForeground(Color.GRAY);
        jRadioButton1Gusto.setForeground(Color.GRAY);
    }

    private void obtenerImagenSuperiorEraDeHielo(){
        ImageIcon imagen1 = new ImageIcon(getClass().getResource("/imagenes/heladeriaherahuielo.jpg"));
        Icon fondo1 = new ImageIcon(imagen1.getImage().getScaledInstance(lbERADEHIELO.getWidth(), lbERADEHIELO.getHeight(), Image.SCALE_DEFAULT));
        lbERADEHIELO.setIcon(fondo1);
        this.repaint();
    }
}
